src/routes.js
src/views/CommonCode/DistrictSelection.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/QualificationTableEdit.jsx
src/views/Master/BankMaster/BankMastTable.jsx
src/views/Master/BankMaster/BankMastTableEdit.jsx
src/views/Master/Designation/DesignationMastTableEdit.jsx
src/views/Master/Designation/DesignationTable.jsx
src/views/Master/Region/RegionMastTable.jsx
src/views/Master/Region/RegionMastTableEdit.jsx

Edit pages of Designation master and bank Master

Edit pages of Designation master,bank Master

---

package-lock.json
src/routes.js
src/views/Master/BankMaster/BankMaster.jsx
src/views/Master/BranchMaster/BranchMastTable.jsx
src/views/Master/BranchMaster/BranchMastTableEdit.jsx
src/views/Master/Region/RegionMastTableEdit.jsx
yarn.lock

Edit master files branch

---

src/views/CommonCode/BrnachMastSelection.jsx
src/views/CommonCode/DepartmentSectionSelect.jsx
src/views/CommonCode/DepartmentSelect.js
src/views/CommonCode/DoctorType.jsx
src/views/CommonCode/EmployeeCategory.jsx
src/views/CommonCode/EmployeeInstitutiontype.jsx
src/views/CommonCode/GradeeSelect.jsx
src/views/CommonCode/Salutation.jsx
src/views/Component/TextInput.js
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx

employyee record page updated using Textinput component

employyee record page updated using Textinput

---

src/routes.js
src/views/CommonCode/ReligionSelect.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/Master/DesignationType/DesignationTypeTable.jsx
src/views/Master/DesignationType/DesignationTypeTableedit.jsx
src/views/Master/EmploymentType/EmploymentTypeMast.jsx

modify employee record by using footer

modify employee record by using footer

---

src/routes.js
src/views/Component/MinutePicker.js
src/views/Component/Timepicker.js
src/views/EmployeeRecord/EmployeeFile/ContractInformation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeExperience.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/EmployeeExperienceEdit.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx
src/views/Master/ShiftMaster/ShiftMasterTable.jsx

shift master and employee experience error corrected

shift master and employee experience error corrected

---

src/Context/MasterContext.js
src/routes.js
src/views/CommonCode/BankNameSelect.jsx
src/views/CommonCode/RegionSelect2.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile.jsx
src/views/EmployeeRecord/EmployeeFile/PersonalInformation.jsx
src/views/EmployeeRecord/EmployeeFile/StatutoryInformation.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/Master/BankMaster/BankMaster.jsx
src/views/Master/EmploymentType/EmploymentTypeEdit.jsx
src/views/Master/EmploymentType/EmploymentTypeMast.jsx
src/views/pages/login/Login.js

employee personal information insert page completed

employee personal information insert page completed

---

src/Context/MasterContext.js
src/routes.js
src/views/CommonCode/ModalOne.jsx
src/views/CommonCode/WageDescripErnDeductSelect.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/EmpAllowanceTableEdit.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/QualificationTableEdit.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileTable/QualificationTable.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileTable/WagesInfoTable.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeQualification.jsx

Employee allowance page insertion and edit and also modify the emp qualification pages 
and chance the route based on employee id and no

Employee allowance page insertion and edit and also modify the emp qualification pages 

---

src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/EmployeeProfileCardMenuList.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/QualificationTableEdit.jsx
src/views/EmployeeRecord/EmployeeFile/PersonalInformation.jsx
src/views/Master/BankMaster/BankMaster.jsx

Employee profile card edited

---

src/Menus/LeaveManagemrent.js
src/routes.js
src/views/Attendance/ApprovalHOD/ApprovalHod.jsx
src/views/Attendance/ApprovalHR/ApprovalHR.jsx
src/views/Attendance/ApprovalIncharge/ApprovalIncharge.jsx
src/views/Attendance/LeaveCancelEmployee/LeaveCancelEmploye.jsx
src/views/Attendance/LeaveCancelHR/LeaveCancelHr.jsx
src/views/Attendance/LeaveRequest/LeaveRequest.jsx
src/views/Attendance/OTApprovalHOD/OTApprovalHOD.jsx
src/views/Attendance/OTApprovalHR/OTApprovalHR.jsx
src/views/Attendance/OTApprovalIncharge/OTApprovalIncharge.jsx
src/views/Attendance/OTUpdation/OTUpdation.jsx
src/views/Attendance/OverTimeRequest/OTRequest.jsx

create folder and main page of Leave Management

 create folder and main page of Leave Management

---

src/Context/MasterContext.js
src/views/CommonCode/EarnType.jsx
src/views/CommonCode/GetWageType.jsx
src/views/EmployeeRecord/AllowanceDeducation/AllowanceBulkUpdation.jsx
src/views/EmployeeRecord/AllowanceDeducation/AllowanceDeducation.js
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/FixedWagesSalaryIncre.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelSalaryIncrement.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/SalaryBulkUpdationMainCard.jsx

allowance and deduction bulk updation

allowance and deduction bulk updation

---

src/views/CommonCode/PageLayoutSave.jsx
src/views/LeaveManagement/ApprovalHOD/ApprovalHod.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHRTable.jsx
src/views/LeaveManagement/ApprovalIncharge/ApprovalIncharge.jsx
src/views/LeaveManagement/ApprovalIncharge/ApprovalInchargeTable.jsx
src/views/LeaveManagement/LeaveCancelEmployee/LeaveCancelEmpTable.jsx
src/views/LeaveManagement/LeaveCancelEmployee/LeaveCancelEmploye.jsx
src/views/LeaveManagement/LeaveCancelHR/LeaveCancelHRTable.jsx
src/views/LeaveManagement/LeaveCancelHR/LeaveCancelHr.jsx
src/views/LeaveManagement/LeaveCommonComponent/ModelApproveReject.jsx
src/views/LeaveManagement/LeaveCommonComponent/ModelDelete.jsx
src/views/LeaveManagement/LeaveCommonComponent/ModelOTApprove.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHOD.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHODTable.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHR.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHRTable.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalIncharge.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeTable.jsx
src/views/LeaveManagement/OTUpdation/OTUpdation.jsx
src/views/LeaveManagement/OTUpdation/OTUpdationTable.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx

Leave and OT approval ,rejection pages design

Leave and OT approval ,rejection pages design

---

src/Context/MasterContext.js
src/views/CommonCode/Employeedetails.jsx
src/views/Home/Home.js
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx

created new component for getting employee details

created new component for getting employee details

---

src/components/AppHeader.js
src/components/AppSidebar.js
src/views/Attendance/DutyPlanning/DropDownList.jsx
src/views/Attendance/DutyPlanning/DutyPlanning.jsx
src/views/CommonCode/EmployeeSelect.jsx
src/views/CommonCode/Employeedetails.jsx
src/views/LeaveManagement/LeaveRequest/Component/TestLeaveType.jsx
src/views/LeaveManagement/LeaveRequest/DirLeaveRequest.jsx
src/views/LeaveManagement/LeaveRequest/LeaveDateSelection.jsx
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx
src/views/Master/DepartmentShift/DepartmentShiftTable.jsx
src/views/Master/LeaveTypeMaster/LeaveTypeMast.jsx
src/views/Master/LeaveTypeMaster/LeaveTypeMastEdit.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx

changes in module rights,context for employee details

changes in module rights,context for employee details

---

src/Context/MasterContext.js
src/views/Attendance/DutyPlanning/DepartmentShiftSelect.jsx
src/views/Attendance/DutyPlanning/DropDownList.jsx
src/views/Attendance/DutyPlanning/DutyPlanning.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/CommonCode/DoctorType.jsx
src/views/CommonCode/EmployeeNameSelect.jsx
src/views/CommonCode/EmployeeSelect.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx

duty planning

---

src/Context/MasterContext.js
src/views/CommonCode/DeptSecSelectAuth.jsx
src/views/CommonCode/EmpNameSelectDeptSec.jsx
src/views/Master/AuthorisationHod/HodMarking.jsx
src/views/Master/AuthorisationHod/HodMarkingTable.jsx
src/views/Master/Designation/DesignationMast.jsx
src/views/Master/Designation/DesignationMastTableEdit.jsx
src/views/Master/Designation/DesignationTable.jsx

Authorization Assign Master Completed

Authorization Assign Master Completed

---

src/views/Master/AuthorisationHod/HodAuthorisation.jsx
src/views/Master/AuthorisationHod/MarkingComponent.jsx

CO assign Completed

---

src/Menus/Resignation.js
src/views/Resignation/ResignationApproval/ResignationApprovalIncharge.jsx

Inteliqo najma

---

src/views/LeaveManagement/OTApprovalIncharge/OTApprovalIncharge.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeTable.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx
src/views/Master/AuthorisationHod/HodAuthorisation.jsx
src/views/Master/AuthorisationHod/MarkingComponent.jsx

 CO assign Modification

---

src/Menus/LeaveManagemrent.js
src/_nav.js
src/routes.js
src/views/LeaveManagement/OTApprovalCEO/ModelCEOApproval.jsx
src/views/LeaveManagement/OTApprovalCEO/OTApprovalCEO.jsx
src/views/LeaveManagement/OTApprovalCEO/OTApprovalCEOTable.jsx
src/views/LeaveManagement/OTApprovalHOD/ModelHodApproval.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHOD.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHODTable.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHodSecTable.jsx
src/views/LeaveManagement/OTApprovalHR/ModelHRApproval.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHR.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHRTableSec.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalIncharge.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeSecTable.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeTable.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx
src/views/Master/AuthorisationHod/HodMarking.jsx

OT request and approval completed

OT request and approval completed

---

src/Menus/LeaveManagemrent.js
src/Menus/SettingMenu.js
src/routes.js
src/views/LeaveManagement/LeaveCommonComponent/ModelOTApprove.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHR.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx
src/views/Master/OTWageMaster/OTWageMastTable.jsx
src/views/Master/OTWageMaster/OTWageMaster.jsx
src/views/Master/OTWageMaster/OTWageTableEdit.jsx

OT wage master completed

---

src/Menus/Resignation.js
src/Menus/SettingMenu.js
src/routes.js
src/views/Attendance/DutyPlanning/DepartmentShiftSelect.jsx
src/views/Master/DepartmentShift/DepartmentShiftEdit.jsx
src/views/Master/DepartmentShift/DepartmentShiftMast.jsx
src/views/Master/DueClearenceDepartment/DueClearenceDepartment.jsx
src/views/Master/DueClearenceDepartment/DueClearenceDeptEdit.jsx
src/views/Master/DueClearenceMaster/DueClearenceEdit.jsx
src/views/Master/DueClearenceMaster/DueClearenceMastTable.jsx
src/views/Master/DueClearenceMaster/DueClearenceMaster.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Resignation/DueClearence/DeptClearence.jsx
src/views/Resignation/DueClearence/DueClearenceApprovalModel.jsx
src/views/Resignation/DueClearence/DueClearenceTable.jsx
src/views/Resignation/DueClearence/DutyHandover.jsx
src/views/Resignation/DueClearenceHR/Checkboxcompnt.jsx
src/views/Resignation/DueClearenceHR/DueApprovalHrCompoent.jsx
src/views/Resignation/DueClearenceHR/DueClearenceHR.jsx
src/views/Resignation/DueClearenceHR/DueClearenceHRTable.jsx
src/views/Resignation/DueClearenceHR/DueclearenceHrModel.jsx
src/views/Resignation/ResignationApproval/ResignationApprovalIncharge.jsx
src/views/Resignation/ResignationApprovalCEO/CeoApprovalTable.jsx
src/views/Resignation/ResignationApprovalHR/ContractCloseHRApproval.jsx
src/views/Resignation/ResignationApprovalHR/ContractCloseHrApprovalModel.jsx
src/views/Resignation/ResignationApprovalHR/ResignationApprovalHR.jsx
src/views/Resignation/ResignationComponent/HodResignationApproval.jsx

resignation process completed,
resignation request,approval incharge,hod,ceo,
resignation cancel,
due clearence,due clearence hr

resignation process completed

---

src/Menus/Resignation.js
src/routes.js
src/views/Attendance/DutyPlanning/DepartmentShiftSelect.jsx
src/views/EmployeeRecord/EmployeeFile/ContractInformation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeExperience.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/EmployeeExperienceEdit.jsx
src/views/Resignation/EmployeeReport/EmployeeInactiveTable.jsx
src/views/Resignation/EmployeeReport/EmployeeReport.jsx
src/views/Resignation/EmployeeReport/EmployeeReportInactive.jsx
src/views/Resignation/EmployeeReport/EmployeeReportTable.jsx

report-employee list with status active,incative,contract closed

report-employee list with status active,incative,contract closed

---

src/Menus/LeaveManagemrent.js
src/views/LeaveManagement/OTApprovalCEO/ModelCEOApproval.jsx
src/views/LeaveManagement/OTApprovalCEO/OTApprovalCEOTable.jsx
src/views/LeaveManagement/OTApprovalHOD/ModelHodApproval.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHODTable.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHodSecTable.jsx
src/views/LeaveManagement/OTApprovalHR/ModelHRApproval.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHRTable.jsx
src/views/LeaveManagement/OTApprovalHR/OTApprovalHRTableSec.jsx
src/views/LeaveManagement/OTApprovalIncharge/ModelInchargeApproval.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeSecTable.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeTable.jsx
src/views/LeaveManagement/OTComponent/OTCancelModel.jsx

over time cancel of incahrge, hod, ceo and hr

over time cancel

---

src/views/LeaveManagement/LeaveRequest/Component/Compenofflpundata.jsx
src/views/LeaveManagement/OTComponent/GetPunchdata.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx

Over Time Modification

---

src/redux/actions/Department.action.js
src/redux/actions/DeptSection.action.js
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwad.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/FineAndDeductionTableEdit.jsx
src/views/EmployeeRecord/EmployeeFile/FineorDeduction.jsx
src/views/LeaveManagement/OTApprovalCEO/ModelCEOApproval.jsx
src/views/LeaveManagement/OTApprovalHOD/ModelHodApproval.jsx
src/views/LeaveManagement/OTApprovalHOD/OTApprovalHODTable.jsx
src/views/LeaveManagement/OTApprovalIncharge/ModelInchargeApproval.jsx
src/views/LeaveManagement/OTApprovalIncharge/OTApprovalInchargeTable.jsx
src/views/LeaveManagement/OTComponent/GetPunchdata.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx
src/views/LeaveManagement/OverTimeRequest/OTRequestTable.jsx

Modifications

---

package-lock.json
src/views/LeaveManagement/LeaveRequest/LeaveCalender.jsx
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx
src/views/Resignation/ResigantionRequest/ResignationRequest.jsx
src/views/Resignation/ResignationComponent/HRApprovalComponent.jsx
yarn.lock

Error correction

---

src/Menus/EmployeeRecord.js
src/Menus/LeaveManagemrent.js
src/routes.js
src/views/Attendance/AttendanceMarking/AttendanceMarking.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdationTable.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdationTblRow.jsx
src/views/Attendance/ShiftUpdation/Shiftfirstcol.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Contract_detl_table.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Contract_end_details.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Contractdetl_TableByDate.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Probation_End_Table.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Probation_End_TableByDate.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Probation_end_details.jsx
src/views/LeaveManagement/NightOff/NightOffRequest.jsx
src/views/Resignation/ResignationApproval/InchargeApprovalTable.jsx

Night off calculation

---

src/Menus/EmployeeRecord.js
src/components/AppHeader.js
src/components/profileComponent/AlertComponent.jsx
src/components/profileComponent/MessageComponent.js
src/components/profileComponent/MessageComponents.jsx
src/components/profileComponent/NotificationComponent.js
src/redux/actions/Alert.Actions.js
src/redux/actions/Message.actions.js
src/redux/constants/action.type.js
src/redux/reducers/AlertReducres.js
src/redux/reducers/MessageReducres.js
src/redux/reducers/index.js
src/routes.js
src/views/Attendance/DutyPlanning/DepartmentShiftSelect.jsx
src/views/EmployeeRecord/Hrm_Alert/Hrm_Alert.jsx
src/views/EmployeeRecord/Hrm_message/Hrm_message.jsx
src/views/Master/DesignationType/DesignationTypeMast.jsx
src/views/Master/EmploymentType/EmploymentTypeMast.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx

Alert and Message

---

src/Menus/EmployeeRecord.js
src/components/profileComponent/NotificationComponent.js
src/views/EmployeeRecord/Probation_Contract_End_Details/Contract_detl_table.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Contractdetl_TableByDate.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Probation_End_Table.jsx
src/views/EmployeeRecord/Probation_Contract_End_Details/Probation_End_TableByDate.jsx
src/views/Resignation/ResignationApprovalHR/ResignationApprovalHR.jsx

Error Corrected

---

src/views/LeaveManagement/OverTimeRequest/OTRequest.jsx

OT modified

---

package.json
src/Menus/AttendanceMang.js
src/routes.js
src/views/Attendance/AnnualLeaveProcess/AnnualLeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/Leavprccompnt.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryCount.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwad.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryTextFeild.jsx
src/views/CommonCode/AnnualProcessComponent.jsx
src/views/EmployeeRecord/EmployeeFile/AnnualLeaveSettings.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelAvailLeavelist.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelLeaveProcess.jsx

Yearly process completed and attendance marking

Yearly process completed and attendance marking

---

src/components/profileComponent/MessageComponent.js
src/components/profileComponent/NotificationComponent.js
src/views/Attendance/DutyPlanning/DutyPlanning.jsx
src/views/CommonCode/GradeSelect.jsx
src/views/EmployeeRecord/EmployeeFile/AnnualLeaveSettings.jsx
src/views/EmployeeRecord/EmployeeFile/ContractInformation.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/CarryForwardLeaveList.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ContractRenewModel.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelLeaveProcess.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeExperience.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/EmployeeExperienceEdit.jsx
src/views/EmployeeRecord/EmployeeFile/StatutoryInformation.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx
src/views/Master/ShiftMaster/ShiftMasterTable.jsx

New Modifications

---

src/redux/actions/Profile.action.js
src/redux/reducers/ProfileDataReducer.js
src/views/EmployeeRecord/EmployeeFile/ApplicationForm.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/MyProfileSalary.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/MyProfleExperience.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/ProfessionalExp.jsx

Profile modification

---

src/views/Attendance/AnnualLeaveProcess/Leavprccompnt.jsx
src/views/Attendance/AttendanceMarking/AttendanceMarkingTabdata.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwad.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryRow.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/Shiftfirstcol.jsx
src/views/CommonCode/AnnualProcessComponent.jsx
src/views/CommonCode/CustomePagination.jsx
src/views/Constant/Constant.js
src/views/EmployeeRecord/EmployeeFile/ApplicationForm.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelAvailLeavelist.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelLeaveProcess.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/AcademicQualCmp.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/AnualLeave.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/MyProfileExpQualify.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/MyProfilePersonalInform.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/MyProfileSalary.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/PersonalDataInform.jsx
src/views/LeaveManagement/NightOff/NightOffRequest.jsx
src/views/LeaveManagement/OTApprovalCEO/ModelCEOApproval.jsx
src/views/LeaveManagement/OTApprovalCEO/OTApprovalCEO.jsx
src/views/LeaveManagement/OTApprovalCEO/OTApprovalCEOTable.jsx
src/views/LeaveManagement/OTApprovalHOD/ModelHodApproval.jsx

 Error correction

---

src/Menus/PayrollMenu.js
src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmployeeFileEdit/FineAndDeductionTableEdit.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeQualification.jsx
src/views/EmployeeRecord/EmployeeFile/FineorDeduction.jsx
src/views/Master/CommonSettings/CommonSettings.jsx
src/views/Payroll/PayrollProcess/EarningTableCell.jsx
src/views/Payroll/PayrollProcess/FixedTableCell.jsx
src/views/Payroll/PayrollProcess/PayrollProcess.jsx
src/views/Payroll/PayrollProcess/PayrollProcessTable.jsx

Fine and deduction modification and payroll process module design

Fine and deduction modification and payroll process module design

---

src/Menus/Resignation.js
src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/EmployeeProfileCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFile.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/Resignation/EmployeeInactiveHR/EmployeeInactiveHR.jsx
src/views/Resignation/EmployeeInactiveHR/EmployeeInactiveTable.jsx
src/views/Resignation/ResignationComponent/HRApprovalComponent.jsx

Page For Inactive Employee,removed In active employee from employee file

Page For Inactive Employee,removed In active employee from employee file

---

src/routes.js
src/views/Attendance/AnnualLeaveProcess/AnnualLeaveProcess.jsx
src/views/Attendance/AttendanceMarking/AttendanceMarking.jsx
src/views/Attendance/DutyPlanning/DutyPlanning.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/EmployeeProfileCard.jsx
src/views/Home/Profile.js
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx
src/views/Resignation/EmployeeInactiveHR/EmployeeInactiveHR.jsx

new changes

---

src/views/LeaveManagement/LeaveRequest/Component/Compensatoryoff.jsx
src/views/LeaveManagement/LeaveRequest/Component/InchargeLeaveReqEmp.jsx
src/views/LeaveManagement/LeaveRequest/Component/LeaveCancelUserModel.jsx
src/views/LeaveManagement/LeaveRequest/Component/LeaveSingleSelection.jsx
src/views/LeaveManagement/LeaveRequest/Component/TestCasulLeave.jsx
src/views/LeaveManagement/LeaveRequest/Component/TestLeaveType.jsx
src/views/LeaveManagement/LeaveRequest/DirLeaveRequest.jsx
src/views/LeaveManagement/LeaveRequest/HalfDayLeaveRequest.jsx
src/views/LeaveManagement/LeaveRequest/LeaveCalender.jsx
src/views/LeaveManagement/LeaveRequest/LeaveDateSelection.jsx
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx
src/views/LeaveManagement/LeaveRequest/LeaveRequestTable.jsx
src/views/LeaveManagement/LeaveRequest/NoPunchRequest.jsx

Leave Cncel user,Leave Request by Incharge

Leave Cncel user,Leave Request by Incharge

---

src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdationTblRow.jsx
src/views/Attendance/ShiftUpdation/Shiftfirstcol.jsx

changes in attendance updation pocess

changes in attendance updation pocess

---

src/Menus/Reports.js
src/Menus/ReportsMenu.js
src/components/AppHeader.js
src/routes.js
src/views/Master/ModuleGroupMaster/ModuleGroupMast.jsx
src/views/Master/ModuleGroupMaster/ModuleGroupMastEdit.jsx

Report menu

---

src/views/EmployeeRecord/EmployeeFile/EmployeeQualification.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescriptionEmployee.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionEdit.jsx

changes in qualification and job description

changes in qualification and job description

---

src/views/CommonCode/RegionSelect.jsx
src/views/CommonCode/RegionSelect2.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescriptionEmployee.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/Resignation/ResigantionRequest/ResignationRequest.jsx

Design Corrections

---

src/views/CommonCode/PageLayoutReports.jsx

reports page layout

---

src/views/Attendance/AnnualLeaveProcess/AnnualLeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/Leavprccompnt.jsx
src/views/Component/Materialtable.js
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelLeaveProcess.jsx
src/views/HrReports/EmployeeReport/EmployeeInactiveTable.jsx
src/views/HrReports/EmployeeReport/EmployeeReportTable.jsx

component for material table

---

src/views/CommonCode/PageLayoutReports.jsx

reports page layout modification

reports page layout modification

---

src/views/Attendance/AnnualLeaveProcess/AnnualLeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/Leavprccompnt.jsx
src/views/EmployeeRecord/EmployeeFile/AnnualLeaveSettings.jsx
src/views/HrReports/EmployeeReport/EmployeeInactiveTable.jsx

new changes in annual leave process

new changes in annual leave process

---

src/views/EmployeeRecord/EmployeeFile/EmployeeFile.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx

chang in employee file search

---

src/views/EmployeeRecord/EmployeeFile/PersonalInformation.jsx
src/views/Master/YearlyLeaveCalendar/YearlyLeaveCalendarMast.jsx

new changes in employee personal information

new changes in employee personal information

---

src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/test.jsx
src/views/Master/EmploymentType/EmploymentTypeEdit.jsx
src/views/Master/EmploymentType/EmploymentTypeMast.jsx

changes in employee category

---

src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx

contract end late calculation corrected

contract end late calculation corrected

---

src/views/Attendance/AttendanceMarking/AttendanceMarkinCardMap.jsx
src/views/Attendance/AttendanceMarking/AttendanceMarkingMainCard.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFile.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/CompetencyDetl.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/DutiesAndresp.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/JobCompetency.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/JobGenericEmp.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/JobSummaryEmp.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/Jobperformance.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/QualificationItem.jsx
src/views/EmployeeRecord/EmployeeFile/JobDescriptionEmployee.jsx
src/views/EmployeeRecord/JobDescription/Competency.jsx
src/views/EmployeeRecord/JobDescription/CompetencyItem.jsx
src/views/EmployeeRecord/JobDescription/DutyRespos.jsx
src/views/EmployeeRecord/JobDescription/ExperienceItem.jsx
src/views/EmployeeRecord/JobDescription/Generic.jsx
src/views/EmployeeRecord/JobDescription/Items.jsx
src/views/EmployeeRecord/JobDescription/JobSummary.jsx
src/views/EmployeeRecord/JobDescription/KraItem.jsx
src/views/EmployeeRecord/JobDescription/Performance.jsx

new changes in job description

new changes in job description

---

src/views/CommonCode/AnnualProcessComponent.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/EmployeeFile/AnnualLeaveSettings.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/CasualLeaveList.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/EarnLeaveList.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/ModelLeaveProcess.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeCompany.jsx

earn leave process

---

src/views/Attendance/AttendanceMarking/AttandanceMarkingtotal.jsx
src/views/Attendance/AttendanceMarking/Avatharattndance.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdationTblRow.jsx
src/views/Attendance/ShiftUpdation/Shiftfirstcol.jsx
src/views/Attendance/styleattnd.css
src/views/CommonCode/AnnualProcessComponent.jsx
src/views/Constant/Static.js
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/ProfileNotverifiedModal.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/ProfileVerificationModal.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFile.jsx

hr modification completed

---

src/views/EmployeeRecord/EmployeeFile/EmployeeFile.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Qualification/QualificationDetails.jsx
src/views/EmployeeRecord/JobDescription/ExperienceItem.jsx

job description experience edit

job description experience edit

---

.gitignore
src/Menus/EmployeeRecord.js
src/routes.js
src/views/Component/CommonAgGrid.jsx
src/views/EmployeeRecord/EmployeeFile/ApplicationForm.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeFileAgGrid.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Profile/ProfileMenus.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Qualification/QualificationDetails.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpVerification/EmployeeSecondVerification.jsx
src/views/Home/Components/AnnouncementList.jsx

Qualification edit correction, announcmentlist rerendering correction

Qualification edit correction, announcmentlist rerendering correction

---

src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/JobDescription/JobDescriptionList.jsx
src/views/EmployeeRecord/JobDescription/Competency.jsx
src/views/EmployeeRecord/JobDescription/DutyRespos.jsx
src/views/EmployeeRecord/JobDescription/Generic.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionViewTable.jsx
src/views/EmployeeRecord/JobDescription/JobSummary.jsx
src/views/EmployeeRecord/JobDescription/Performance.jsx

job description department section added, job description list table

job description department section added, job description list table

---

src/views/Attendance/DutyPlanning/DutyPlanning.jsx
src/views/EmployeeRecord/EmployeeFile/EmpFileComponent/MyProfileCmp/ProfileVerificationModal.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Profile/ProfileMenus.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpVerification/EmployeeFirstVerification.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpVerification/EmployeeSecondVerification.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpVerification/EmployeeVerificationView.jsx
src/views/LeaveManagement/LeaveRequest/Component/InchargeLeaveReqEmp.jsx
src/views/LeaveManagement/LeaveRequest/LeaveRequest.jsx

dutyplanning correction, leave request correction, profile verification

dutyplanning correction, leave request correction, profile verification

---

src/views/Master/KRA/KRA.jsx

KRA  table delete

---

src/views/Master/AuthorisationHod/HodMarking.jsx
src/views/Master/DepartmentShift/DepartmentShiftEdit.jsx
src/views/Master/DepartmentShift/DepartmentShiftMast.jsx

department shift master and Incharge,HOD assign error correction

department shift master and Incharge,HOD assign error correction

---

src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/MenuList.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/MenuRenderWind.js
src/views/EmployeeRecord/JobDescription/Competency.jsx
src/views/EmployeeRecord/JobDescription/CompetencyItem.jsx
src/views/EmployeeRecord/JobDescription/DutyRespos.jsx
src/views/EmployeeRecord/JobDescription/ExperienceItem.jsx
src/views/EmployeeRecord/JobDescription/Generic.jsx
src/views/EmployeeRecord/JobDescription/Items.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionEdit/JobDescriptionEdit.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionViewTable.jsx
src/views/EmployeeRecord/JobDescription/KraItem.jsx
src/views/EmployeeRecord/JobDescription/Performance.jsx

job description correction, profile menu group rights

job description correction, profile menu group rights

---

src/views/EmployeeRecord/EmployeeFile/JobDescEmpComponent/JobGenericEmp.jsx
src/views/EmployeeRecord/JobDescription/Competency.jsx
src/views/EmployeeRecord/JobDescription/CompetencyItem.jsx
src/views/EmployeeRecord/JobDescription/CompetencyWithAgGrid.jsx
src/views/EmployeeRecord/JobDescription/DutyResponsWithAgGrid.jsx
src/views/EmployeeRecord/JobDescription/DutyRespos.jsx
src/views/EmployeeRecord/JobDescription/ExperienceItem.jsx
src/views/EmployeeRecord/JobDescription/Generic.jsx
src/views/EmployeeRecord/JobDescription/Items.jsx
src/views/EmployeeRecord/JobDescription/JobDeletionModal.jsx
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/JobSummary.jsx
src/views/EmployeeRecord/JobDescription/KraItem.jsx
src/views/EmployeeRecord/JobDescription/Performance.jsx
src/views/EmployeeRecord/JobDescription/PerformanceWithAgGrid.jsx
src/views/HrReports/ContractReports/ContractClosedReport.jsx
src/views/HrReports/ContractReports/ContractCurrentRunningReport.jsx
src/views/HrReports/ContractReports/ContractRenewReport.jsx
src/views/HrReports/ContractReports/OneYearCurrentRunning.jsx
src/views/HrReports/EmployeeReport/EmployeeReport.jsx
src/views/HrReports/EmployeeReport/EmployeeReportInactive.jsx
src/views/HrReports/ExperienceReports/ExperienceReport .jsx
src/views/HrReports/PermanentEmployeeReports/PermanentEmployeeReport.jsx
src/views/HrReports/QualificationReport/QualificationReport.jsx

job description corrections, hr report correction

job description corrections, hr report correction

---

src/views/EmployeeRecord/JobDescription/CompetencyWithAgGrid.jsx
src/views/EmployeeRecord/JobDescription/DutyResponsWithAgGrid.jsx
src/views/EmployeeRecord/JobDescription/PerformanceWithAgGrid.jsx

duties, performance, comptency delete rendering correction

duties, performance, comptency delete rendering correction

---

src/views/EmployeeRecord/EmployeeFile/EmployeeFileAgGrid.jsx

removing branch select from employee file search

removing branch select from employee file search

---

src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Function/ContractFun.js
src/views/EmployeeRecord/ContractRenewalProcess/Renew_Process.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Profile/ProfileMenus.js

contract renewal exptable, qualiftable, personaltable api corrected

contract renewal exptable, qualiftable, personaltable api corrected

---

src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Function/ContractFun.js

correct em_no updated in exp, personal, qualif table when permanent cate selected

correct em_no updated in exp, personal, qualif table when permanent cate selected

---

package-lock.json
package.json
src/components/AppSidebar.js
src/redux/actions/JobDescription.Action.js
src/redux/reducers/JobDescription.Reducer.js
src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmployeeFileAgGrid.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/JobDescription/JobDescriptionList.jsx
src/views/EmployeeRecord/JobDescription/JobDescrPdf.js
src/views/EmployeeRecord/JobDescription/JobDescription.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionViewTable.jsx
yarn.lock

login employee name on left sidebar, emp file table handpoint instead of mouse pointer, job description pdf

login employee name on left sidebar, emp file table handpoint instead of mouse pointer, job description pdf

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmployeeFileAgGrid.jsx
src/views/EmployeeRecord/JobDescription/JobDescriptionViewTable.jsx
src/views/HrReports/ExperienceReports/NoExpReport.jsx

no experience employee report, ag grid column column view correction

no experience employee report, ag grid column column view correction

---

src/views/HrReports/ExperienceReports/NoExpReport.jsx
src/views/PerformanceAppraisal/AppraisalComponents/AppraisalView.jsx
src/views/PerformanceAppraisal/CompletedAppraisalList.jsx
src/views/PerformanceAppraisal/HRList.jsx
src/views/PerformanceAppraisal/SelfApproval/SelfApproval.jsx

apprasail correction- self apprasial, report view with slno

apprasail correction- self apprasial, report view with slno

---

src/views/EmployeeRecord/ContractRenewalProcess/AttendanceDetails.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/EXistContractDetl.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Function/ContractFun.js
src/views/EmployeeRecord/ContractRenewalProcess/Old_dataTo_copy.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Renew_Process.jsx

contract renewal process error correction

contract renewal process error correction

---

src/views/LeaveManagement/ApprovalCEO/ApprovalCEO.jsx
src/views/LeaveManagement/ApprovalHOD/HodApproval.jsx
src/views/LeaveManagement/ApprovalIncharge/ApprovalIncharge.jsx
src/views/LeaveManagement/LeaveCommonComponent/CompOffRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/HaldayRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/LeaveManagement/LeaveCommonComponent/NopunchRqModel.jsx

leave approval modification

---

src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx

Punch in/out marking

---

src/Menus/SettingMenu.js
src/routes.js
src/views/Attendance/ShiftUpdation/Function.js
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/Master/PunchTransfer/PunchTransfer.jsx

punch transfer, in  out marking and woff calculations completed

punch transfer, in  out marking and woff calculations completed

---

src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/LeaveCancelHR/HrLeaveCancel.jsx
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/LeaveManagement/LeavereRequsition/MultiLeaveRequestForm.jsx

half day request and no punch request by employee error cleared

half day request and no punch request by employee error cleared

---

src/views/LeaveManagement/LeavereRequsition/LeaveRequestMainCard.jsx

Error correction of leave request apply an employee through HOD/Inharge user

Error correction of leave request apply an employee through HOD/Inharge user

---

src/routes.js
src/views/Attendance/PunchMarkingHR/PunchMarkDoneList.jsx
src/views/Attendance/PunchMarkingHR/PunchMarkingHR.jsx
src/views/Attendance/PunchMarkingHR/PunchSavedHrView.jsx
src/views/Attendance/ShiftUpdation/Function.js

punch in/out mark HR view and delete

punch in/out mark HR view and delete

---

src/views/Axios/Axios.js
src/views/EmployeeRecord/Probation_Contract_End_Details/ContractDetailsAgGrid.jsx
src/views/Payroll/AttendanceUpdation/ExportToExcel.js
src/views/PerformanceAppraisal/AnnualAppraisalList.jsx
src/views/PerformanceAppraisal/ProbationEnd.jsx
src/views/PerformanceAppraisal/TrainingEnd.jsx

training,probation,annual end error correction

training,probation,annual end error correction

---

src/views/Attendance/DutyPlan/DutyPlanFun/DutyPlanFun.jsx
src/views/Attendance/DutyPlan/DutyPlanFun/ShiftSelect.jsx
src/views/Attendance/DutyPlan/DutyPlanMainCard.jsx
src/views/Attendance/PunchMarkingHR/PunchMarkDoneList.jsx

Duty plan Unlock after deleteing Punch save by hr and disable duty plan bulkupdation

Duty plan Unlock after deleteing Punch save by hr and disable duty plan bulkupdation

---

src/views/Master/EarningDeductionMaster/EarnDectEdit.jsx

Earning and deduction master page edit modification

Earning and deduction master page edit modification

---

src/routes.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Qualification/QualificationPage.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Statutory/StatutoryInformation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/ProfileCard.js
src/views/Home/Components/LeavesDashbod.js
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/Master/DepartmentMaster/DepartmentMasterPage.jsx

added clinic/non clinic to department master, qualification pass year halfdayreqst added dispatch

added clinic/non clinic to department master, qualification pass year  halfdayreqst added dispatch

---

src/views/EmployeeRecord/EarnDeduction/EarnDeductionModel.jsx
src/views/EmployeeRecord/EarnDeduction/EarningsDeduction.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/Functions.js

earning deduction correction

---

src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/EarnedLeaveCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessMainCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/PersonalInformation/Personaldetails.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx

correction after testing

---

src/views/Attendance/DutyPlan/DutyPlanTopCard.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewList.jsx
src/views/Home/Components/AnnouncementList.jsx
src/views/Resignation/EmployeeInactiveHR/EmployeeInactiveHR.jsx

inactive emp list, dutyplan deptsect list

inactive emp list, dutyplan deptsect list

---

src/views/Attendance/DutyPlan/DutyPlanTopCard.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestEmployeeSelection.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestForm.jsx
src/views/LeaveManagement/NightOff/NightOffRequest.jsx

tooltip added dutyplan, leave reqst

tooltip added dutyplan, leave reqst

---

src/views/Attendance/DutyPlan/DutyPlanFun/DutyPlanFun.jsx
src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

section selct in dutyplan,punch inout error

 section selct in dutyplan,punch inout error

---

src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/DutyPlan/DutyPlanTopCard.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Function/ContractFun.js
src/views/EmployeeRecord/EmployeeFile/EmployeeFileAgGrid.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessCard.jsx
src/views/LeaveManagement/NightOff/NightOffRequest.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

dutyplan, leave process sick leave, contract renewal password

dutyplan, leave process sick leave, contract renewal password

---

src/components/AppSidebar.js
src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Function/ContractFun.js
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestForm.jsx
src/views/LeaveManagement/LeavereRequsition/MultiLeaveRequestForm.jsx
src/views/LeaveManagement/NightOff/NightOffRequest.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx
src/views/MuiComponents/JoyComponent/HodWiseDeptSection.jsx
src/views/pages/login/Login.js

login error, punch inout correct,

login error, punch inout correct,

---

src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx

punch inoutmrking, leav reqst conditn

punch inoutmrking, leav reqst conditn

---

src/views/Attendance/ShiftUpdation/Function.js

punch in out

---

src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/LeaveManagement/LeavereRequsition/MultiLeaveRequestForm.jsx

noff direct dutyplan

---

src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/Master/CommonSettings/CommonSettingNew.jsx

noff showing punch inout, leave approval func

noff showing punch inout, leave approval func

---

src/views/LeaveManagement/CommonRequest/Approvals/HodApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx

approvl list

---

src/views/Attendance/AttendanceView/AttendanceView.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/LeaveManagement/ApprovalHR/Modal/CompansatoryOff.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstMainPage.jsx
src/views/MuiComponents/JoyComponent/HodWiseEmpList.jsx

punch marking self, one hour correction

punch marking self, one hour correction

---

src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx

attendance view new joinee

---

src/views/Attendance/PunchMarkingHR/DeptSectionComponent.jsx
src/views/Attendance/PunchMarkingHR/PunchMarkingNew.jsx
src/views/HrReports/EmployeeReport/EmployeeReport.jsx
src/views/LeaveManagement/ApprovalHOD/HodApproval.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/CommonRequest/Approvals/HrApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstMainPage.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeaveCancelHR/HrLeaveCancel.jsx
src/views/Master/EmploymentType/EmploymentTypeEdit.jsx

common request correction

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/AttendanceView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/ShiftUpdation/Function.js
src/views/LeaveManagement/LeavereRequsition/Func/RequestedLeaveTable.jsx
src/views/Payroll/AttendanceAutomatic/AttendanceGenerateAuto.jsx

attendance count correction, leaves approval show correction

attendance count correction, leaves approval show correction

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/ShiftUpdation/Function.js
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/LeavereRequsition/CompansatoryOff/CompansatoryOffMast.jsx
src/views/Master/ShiftMaster/ShiftMaster.jsx
src/views/Master/ShiftMaster/ShiftMasterEdit.jsx
src/views/Payroll/AttendanceAutomatic/AttendanceGenerateAuto.jsx
src/views/Payroll/AttendanceRegister/AttandaceRegisterPage.jsx
src/views/Payroll/SalaryStatement/SalaryStatementPage.jsx

salary report, attendance view correction

salary report, attendance view correction

---

src/views/HrReports/Employee Punch Report/EmpPunchReport.jsx
src/views/HrReports/LeaveReports/LeaveReports.jsx

modification

---

src/routes.js
src/views/Attendance/ShiftUpdation/Function.js
src/views/Component/MuiCustomComponent/CustmTypog.jsx
src/views/EmployeeRecord/ContractRenewalProcess/RenewProcess.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessMainCard.jsx
src/views/HrReports/Employee Punch Report/EmpPunchReport.jsx
src/views/HrReports/ReportComponent/ReportWithoutDownload.jsx
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeaveCancelHR/HrLeaveCancel.jsx
src/views/LeaveManagement/LeavereRequsition/CompansatoryOff/CompansatoryOffMast.jsx
src/views/LeaveManagement/LeavereRequsition/Func/RequestedLeaveTable.jsx
src/views/MuiComponents/DesignationSelect.jsx
src/views/Payroll/AttendanceAutomatic/AttendanceGenerateAuto.jsx

salary report, attendance automatic , night shift one hour requst, punch inoutcorrection, leave status view correction

salary report, attendance automatic , night shift one hour requst, punch inoutcorrection, leave status view correction

---

src/redux/actions/LeaveReqst.action.js
src/redux/reducers/Leavereqdata.js
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/LeavereRequsition/Func/CompansatorLeaveSelected.jsx
src/views/Resignation/EmployeeActiveHR/ActiveModal.jsx
src/views/Resignation/EmployeeActiveHR/EmployeeActiveHR.jsx

employee register contract and probation end date month end, remark while activating employee, onehr correction, compensatory correction

employee register contract and probation end date month end, remark while activating employee, onehr correction, compensatory correction

---

src/routes.js
src/views/Attendance/PreviousMonthReport/EmployeePunchReport.jsx
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/LeaveManagement/LeavereRequsition/Func/RequestedLeaveTable.jsx
src/views/Payroll/AttendanceAutomatic/AttendanceGenerateAuto.jsx

without incharge dept section approval, adding lwf, nps to salary report

without incharge dept section approval, adding lwf, nps to salary report

---

src/Menus/AttendanceMang.js
src/views/Attendance/PreviousMonthReport/EmployeePunchReport.jsx
src/views/Attendance/PreviousMonthReport/TableRows.jsx
src/views/HrReports/CategoryReport/CategoryReports.jsx
src/views/HrReports/EmployeeReport/EmployeeReportInactive.jsx
src/views/LeaveManagement/ApprovalHOD/HodApproval.jsx
src/views/LeaveManagement/ApprovalHR/ApprovalHR.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/LeaveManagement/LeavereRequsition/CompansatoryOff/CompansatoryOffMast.jsx
src/views/LeaveManagement/LeavereRequsition/Func/CompansatorLeaveSelected.jsx
src/views/LeaveManagement/LeavereRequsition/Func/RequestedLeaveTable.jsx

credited leaves deduction in lev reqst, correction apllying same coff, without incharge hod approval correction, category report correction

credited leaves deduction in lev reqst, correction apllying same coff, without incharge hod approval correction, category report correction

---

src/views/Attendance/DepartmentSecChange/DepartmentSecChange.jsx
src/views/HrReports/Employee Punch Report/EmpPunchReport.jsx
src/views/HrReports/ReportComponent/ReportWithoutDownload.jsx
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/ApprovalHOD/HodApproval.jsx
src/views/LeaveManagement/ApprovalIncharge/ApprovalIncharge.jsx
src/views/LeaveManagement/CommonRequest/Approvals/HodApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/HrApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/Modals/OndutyReqstModal.jsx
src/views/LeaveManagement/CommonRequest/Approvals/Modals/OneHourReqstModal.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeaveCommonComponent/CompOffRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/HaldayRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/LeaveManagement/LeaveCommonComponent/NopunchRqModel.jsx
src/views/Resignation/EmployeeActiveHR/ActiveModal.jsx
src/views/Resignation/EmployeeActiveHR/EmployeeActiveHR.jsx

incharge, hod lv reqst rejct leave not credit correction, saturdy week off, common requst approval status

incharge, hod lv reqst rejct leave not credit correction, saturdy week off, common requst approval status

---

src/views/Attendance/DutyPlan/DutyPlanFun/DutyPlanFun.jsx
src/views/Attendance/DutyPlan/MasterPage.jsx
src/views/EmployeeRecord/EarnDeduction/EarnDeductionModel.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/Functions.js
src/views/LeaveManagement/CommonRequest/Approvals/HodApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/HrApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OnDutyRequest.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeaveCommonComponent/HaldayRqModel.jsx
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx
src/views/LeaveManagement/LeavereRequsition/MultiLeaveRequestForm.jsx
src/views/LeaveManagement/LeavereRequsition/SingleLeaveRequestForm.jsx

after punch marking hr no leaves can apply correction , salary updation correction

after punch marking hr no leaves can apply correction , salary updation correction

---

src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/LeavereRequsition/CompansatoryOff/CompansatoryOffMast.jsx
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HaldayRequetsMainForm.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx
src/views/LeaveManagement/LeavereRequsition/MultiLeaveRequestForm.jsx
src/views/LeaveManagement/LeavereRequsition/SingleLeaveRequestForm.jsx

leave request condition correction

leave request condition correction

---

src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OnDutyRequest.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx

punch in out marking dutyday ascending order

punch in out marking dutyday ascending order

---

src/Menus/AttendanceMang.js
src/Menus/ReportsMenu.js
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/EmployeeRecord/EarnDeduction/EarnDeductionModel.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OnDutyRequest.jsx

salary report correction

---

src/Menus/AttendanceMang.js
src/Menus/EmployeeRecord.js
src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/DutyPlan/DutyPlanTopCard.jsx
src/views/Attendance/DutyPlan/MasterPage.jsx
src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeavereRequsition/CompansatoryOff/CompansatoryOffMast.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

common setting addition, dutyplan lock, compensatory unlock

common setting addition, dutyplan lock, compensatory unlock

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/HrReports/AttendenceReport/AttendenceReport.jsx
src/views/HrReports/DayWiseAttendence/DayWiseAttendence.jsx
src/views/HrReports/DayWiseAttendence/ExportToExcel.js
src/views/HrReports/EmployeeReport/EmployeeReport.jsx
src/views/HrReports/LeaveReports/LeaveReports.jsx

attendence report

---

src/Menus/AttendanceMang.js
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx

console cleared, menu comment

---

src/views/LeaveManagement/CommonRequest/Approvals/HrApproval.jsx
src/views/LeaveManagement/CommonRequest/Approvals/Modals/OneHourReqstModal.jsx

common request staus view correction

common request staus view correction

---

src/views/LeaveManagement/CompOffRequest/CompensatoryRequest.jsx
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx

coff credit correction and no misspunch in weekoff

coff credit correction and no misspunch in weekoff

---

src/views/HrReports/Salaryreports/SalaryReport.jsx
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx
src/views/LeaveManagement/LeavereRequsition/Func/DepartmentBasedSection.jsx
src/views/LeaveManagement/LeavereRequsition/Func/RequestedLeaveTable.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx

salary report, levae request master all, leave table view

salary report, levae request master all, leave table view

---

src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HalfDayLeaveRequest.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx

leave request select date correction

leave request select date correction

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx

add holiday absent checking condition and woff absent condition

updation holiday check and woff check

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js

week off calculation corrected

week off calculation corrected

---

src/views/HrReports/Salaryreports/SalaryReport.jsx

salary report

---

src/redux/reduxFun/reduxHelperFun.js
src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/DepartmentSecChange/DepartmentSecChange.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestMainCard.jsx

halfday leave request and approval, leave count in attendnace view

halfday leave request and approval, leave count in attendnace view

---

src/redux/reduxFun/reduxHelperFun.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/PersonalInformation/Personaldetails.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveTableContainer.jsx
src/views/Master/BankMaster/BankBranchselection.jsx
src/views/MuiComponents/BloodgrpSelectRedux.jsx
src/views/MuiComponents/RegionSelectRedux.jsx
src/views/MuiComponents/ReligionSelectRedux.jsx

personal information correction

personal information correction

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/CommonRequest/Approvals/Modals/OneHourReqstModal.jsx
src/views/LeaveManagement/CommonRequest/TableViewPage.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestDocModal.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveTableContainer.jsx

leave request submit modal for verifying leave

leave request submit modal for verifying leave

---

src/views/Attendance/SalaryProcess/SalaryProcessed.jsx

salary report total pay day count correction

salary report total pay day count correction

---

src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx

attendnace view correction for incharge/ hod view

attendnace view correction for incharge/ hod view

---

src/views/HrReports/AttendenceReport/AttendenceReport.jsx
src/views/HrReports/DayWiseAttendence/DayWiseAttendence.jsx

changes in attendence report

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/HrReports/DutyplanReport/DutyPlanReport.jsx

dutyplan report

---

src/Menus/LeaveManagemrent.js
src/routes.js
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/Attendance/SalaryProcess/SalaryProcessed.jsx
src/views/LeaveManagement/OnObservation/ObservationModal.jsx
src/views/LeaveManagement/OnObservation/OnobservationRequest.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

on observation request for new joinees, holiday 6 hr setting

on observation request for new joinees, holiday 6 hr setting

---

src/views/Attendance/DutyPlan/DutyPlanFun/InchargeDutypalnTop.jsx
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/Attendance/SalaryProcess/SalaryProcessed.jsx
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeaveApprovalFunc.js
src/views/LeaveManagement/LeavereRequsition/LeaveRequestDocModal.jsx
src/views/LeaveManagement/OnObservation/ObservationModal.jsx
src/views/LeaveManagement/OnObservation/OnobservationRequest.jsx

shift updation delete button, halfdaytime correction

shift updation delete button, halfdaytime correction

---

src/views/TrainingDevelopment/InductionTest/EmpHomepage.jsx
src/views/TrainingDevelopment/TrainingTopicQuestion/Topic/TopicPage.jsx

Lowercase error cleared

---

src/views/HrReports/DayWiseAttendence/DayWiseAttendence.jsx

department wise day attendance report

department wise day attendance report

---

src/App.js
src/routes.js
src/views/Master/TrainingTopicMaster/TrainingTopic.jsx
src/views/TrainingDevelopment/EmployeeRights/EmployeeRights.jsx
src/views/TrainingDevelopment/EmployeeRights/HodInchargeDashboardView.jsx
src/views/TrainingDevelopment/InductionTest/EmpHomepage.jsx
src/views/TrainingDevelopment/InductionTest/FeedbackPage.jsx
src/views/TrainingDevelopment/InductionTest/Induction_test_login.jsx
src/views/TrainingDevelopment/InductionTest/PostTest/HeadingPage.jsx
src/views/TrainingDevelopment/InductionTest/PostTest/SubmitModal.jsx
src/views/TrainingDevelopment/TrainingCalender/InductionCalenderFormat.jsx
src/views/TrainingDevelopment/TrainingDashboard/TnDViewComponents/TndDashboardView.jsx

Feedback updation

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx

attendance hp correction

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/SalaryProcess/SalaryProcessed.jsx

salary report ifsc, attendance view obs

salary report ifsc, attendance view obs

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/SalaryProcess/SalaryProcessed.jsx
src/views/LeaveManagement/CommonRequest/Approvals/InchargeApproval.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestDocModal.jsx

salary report correction , correction in same leave can apply same date

salary report correction , correction in same leave can apply same date

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/Attendance/DutyPlan/InchargeDutyplan.jsx
src/views/HrReports/OnDutyReport/OndutyReport.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx

on duty report and sick leave reject correction

on duty report and sick leave reject correction

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js

monthly punch marking holiday after weekoff error correction

monthly punch marking holiday after weekoff error correction

---

src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessMainCard.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OnDutyRequest.jsx

onduty save after selecting shift

onduty save after selecting shift

---

src/Menus/LeaveManagemrent.js
src/redux/reduxFun/reduxHelperFun.js
src/routes.js
src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/SalaryProcess/SalaryProcessed.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/EmployeeRecord/CompanyInformationLeftMenu/CompanyInfoPage.jsx
src/views/EmployeeRecord/CompanyInformationLeftMenu/ContractConfirmationModal.jsx
src/views/EmployeeRecord/CompanyInformationLeftMenu/PermanentConfirationModal.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx
src/views/PerformanceAppraisal/CompanyChange.jsx
src/views/PerformanceAppraisal/ProbationEnd.jsx

category external trainee to other change, cl showing till month, hd leave without punch

category external trainee to other change, cl showing till month, hd leave without punch

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/EmployeeRecord/Hrm_Announcement/Hrm_Announcement.jsx
src/views/EmployeeRecord/Hrm_message/Hrm_message.jsx
src/views/HrReports/LeaveCountReport/CreditedLeaveCountReport.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

credite leave count report, anouncement, message page to joy

credite leave count report, anouncement, message page to joy

---

src/views/Attendance/SalaryProcess/SalaryProcessed.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx
src/views/Resignation/EmployeeActiveHR/ActiveModal.jsx
src/views/Resignation/EmployeeInactiveHR/RemarkModal.jsx

attendance report after salary process, leave date error while leaverequsting, login deactivate while inactivating employee

attendance report after salary process, leave date error while leave attendance report after salary process, leave date error while leave

---

src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx

manual request for employees by hr, and leave hr approval correction

manual request for employees by hr, and leave hr approval correction

---

src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx

employee register cant edit contract to permanent, reason mandatory, lv desc and duty desc show, allow default and A in manual request

employee register cant edit contract to permanent, reason mandatory, lv desc and duty desc show, allow default and A in manual request

---

src/redux/reduxFun/reduxHelperFun.js
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/LeaveManagement/ManualRquest/DeleteModal.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx

manual request view ,delete, leave status request page, punch in out marking halfday same punch in correction

manual request view ,delete, leave status request page, punch in out marking halfday same punch in correction

---

src/Menus/LeaveManagemrent.js
src/redux/reduxFun/reduxHelperFun.js
src/routes.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/TableRows.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/HrReports/DayWiseAttendence/DayWiseAttendence.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/LeaveCancelByHR.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/HalfdayModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/LeaveRqModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/MisspunchModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/OnDutyModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/OneHourModal.jsx
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx
src/views/LeaveManagement/LeavereRequsition/HalfdayRequest/HalfDayLeaveRequest.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx
src/views/LeaveManagement/ManualRquest/DeleteModal.jsx
src/views/LeaveManagement/ManualRquest/FileViewmodal.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx
src/views/LeaveManagement/OnObservation/DeleteModal.jsx
src/views/LeaveManagement/OnObservation/OnobservationRequest.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx
src/views/MuiComponents/JoyComponent/JoySectionWiseEmployee.jsx

holiday leave setting condition

holiday leave setting condition

---

src/Menus/LeaveManagemrent.js
src/Menus/Reports.js
src/Menus/ReportsMenu.js
src/routes.js
src/views/LeaveManagement/DOFFRequest/DOFFRequestMain.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx
src/views/PerformanceAppraisal/CompanyChange.jsx

reports changed, probation change date changed

reports changed, probation change date changed

---

src/views/LeaveManagement/OffRequest/RequestComponents/DoffCancelModal.jsx
src/views/LeaveManagement/OffRequest/RequestComponents/DoffSubmitForm.jsx

locking doff request deletion after salary process

locking doff request deletion after salary process

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/LeaveManagement/CompOffRequest/InchargeHodPage.jsx

doff and credit off hod selection dept disable

doff and credit off hod selection dept disable

---

src/components/header/AppHeaderDropdown.js
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

halfday time count and punch taken count common settings

halfday time count and punch taken count common settings

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OneHourRequest.jsx

one hour request afternoo in time correction

one hour request afternoo in time correction

---

src/Menus/ReportsMenu.js
src/views/HrReports/DutyplanReport/DutyPlanReport.jsx

dutyplan report with excel download

dutyplan report with excel download

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/LeaveManagement/ManualRquest/ManualRequestMain.jsx

manual request for already worked staff and showing manual request present showing color change in attendance view

manual request for already worked staff and showing manual request present showing color change in attendance view

---

src/views/LeaveManagement/ApprovalHR/Modal/NoPunchLeaveRequest.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

common setting checkbox view correction

common setting checkbox view correction

---

src/Menus/LeaveManagemrent.js
src/Menus/ReportsMenu.js
src/routes.js
src/views/Attendance/DutyPlan/DutyPlanMainCard.jsx
src/views/HrReports/ManualRequestReport/ManualReqstReport.jsx
yarn.lock

manual request report

---

src/views/Home/Components/DashAlertCmp.js
src/views/Home/Components/TestCmp.jsx
src/views/LeaveManagement/ApprovalHR/Modal/HalfDayLeaveRequest.jsx
src/views/LeaveManagement/ApprovalHR/Modal/NoPunchLeaveRequest.jsx
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx

coff credit week off dutyplan disable

coff credit week off dutyplan disable

---

src/views/Attendance/AttendanceView/AllView.jsx
src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Home/Components/Announcement.js
src/views/Home/Components/AnnouncementList.jsx
src/views/LeaveManagement/LeavereRequsition/LeaveRequestFormNew.jsx

same sick leave can apply correction, obs count in added attendnace view

same sick leave can apply correction, obs count in added attendnace view

---

src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewList.jsx
src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Direct_Contract_Close.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/LeaveProcessMainCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/PersonalInformation/Personaldetails.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecord.jsx
src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/PerformanceAppraisal/ProbationEnd.jsx

leave process after contract renewal correction, adding father or spouse name to personal details

leave process after contract renewal correction, adding father or spouse name to personal details

---

src/views/EmployeeRecord/Hrm_Alert/Hrm_Alert.jsx

alert message deisgn changed

---

src/views/EmployeeRecord/EmployeeRegister/EmployeeRecordEdit.jsx
src/views/Master/CommonSettings/CommonSettingNew.jsx

emp register edit holiday type error

emp register edit holiday type error

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/HrReports/TrainingDevelopmentReports/DepartmentalTrainingReports/DepmtlAttendPendingList.jsx
src/views/HrReports/TrainingDevelopmentReports/DepartmentalTrainingReports/DeptStaffExamReport.jsx
src/views/HrReports/TrainingDevelopmentReports/DepartmentalTrainingReports/DeptYearlyCalender.jsx
src/views/HrReports/TrainingDevelopmentReports/DepartmentalTrainingReports/MonthlyDepartmentalTrainingReports.jsx

Completed Departmental Training Reports

Completed Departmental Training Reports

---

src/views/Attendance/DutyPlan/DutyPlanFun/DutyPlanFun.jsx
src/views/LeaveManagement/OffRequest/RequestComponents/DoffSubmitForm.jsx

doff request correction

---

src/views/LeaveManagement/OnObservation/ObservationModal.jsx
src/views/LeaveManagement/OnObservation/OnobservationRequest.jsx

OBS not update in punch master correction

OBS not update in punch master correction

---

src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/EarnDeductionDetails/EarnDeduction.jsx
src/views/HrReports/DayWiseAttendence/DayWiseAttendence.jsx

attendance report new joinees list showing error correction

attendance report new joinees list ahoeing error correction

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx

punch marking error during default shift on holiday showing absent

punch marking error during default shift on holiday showing absent

---

src/views/LeaveManagement/OffRequest/RequestComponents/DoffSubmitForm.jsx

doff request error correction hh:mm instead of HH:mm

doff request error correction hh:mm instead of HH:mm

---

src/redux/reduxFun/reduxHelperFun.js

halfday correction

---

src/views/HrReports/LeaveCountReport/CreditedLeaveCountReport.jsx

credited leave report with prevoius year and month wise select

credited leave report with prevoius year and month wise select

---

src/Menus/AttendanceMang.js
src/routes.js
src/views/Attendance/AnnualLeaveProcess/AnnualLeaveComponents/LeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/AnnualLeaveComponents/LeaveProcessModal.jsx
src/views/Attendance/AnnualLeaveProcess/AnnualLeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/EmployeeAnnualLeaveProcess.jsx
src/views/Attendance/AnnualLeaveProcess/Leavprccompnt.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryCount.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwad.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryRow.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js

annual leave process

---

src/redux/reduxFun/reduxHelperFun.js

leave query recorrected

---

src/Menus/ReportsMenu.js
src/routes.js
src/views/Attendance/SalaryProcess/MonthlySalaryProcess.jsx
src/views/HrReports/LeaveCountReport/YearlyLeaveCount.jsx
src/views/HrReports/WeekOffReport/WeekOffReport.jsx

previous year leave count report

previous year leave count report

---

src/views/HrReports/AttendenceReport/AttendenceReport.jsx

attendance punch report correction

attendance punch report correction

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/HrReports/AttendenceReport/AttendenceReport.jsx

attendnace report with dept and section only

attendnace report with dept and section only

---

src/redux/reduxFun/reduxHelperFun.js
src/views/HrReports/AttendenceReport/AttendenceReport.jsx
src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/ApprovedleaveCancel/ModalComponents/LeaveRqModal.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx
src/views/LeaveManagement/LeavereRequsition/EmpView/LeaveCancelEmp.jsx
src/views/Resignation/ResigantionRequest/Approvals/InchargeApprovalModal.jsx

when cancelling leave status updated to hrm_leavrq_detl table

when cancelling leave status updated to hrm_leavrq_detl table

---

src/Menus/AttendanceMang.js
src/redux/reduxFun/reduxHelperFun.js
src/routes.js
src/views/Attendance/LeaveCarryForwad/DeptTableView.jsx
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwardMain.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/CasualLeaveCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/EarnedLeaveCard.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/LeaveProcess/Functions/LeaveProcessFun.js
src/views/Master/MenuCreationMaster/MenuCreation.jsx
src/views/MuiComponents/JoyComponent/JoyLeaveType.jsx

previous year leave carryforward

previous year leave carryforward

---

src/Menus/ReportsMenu.js
src/redux/reduxFun/reduxHelperFun.js
src/routes.js
src/views/Attendance/LeaveCarryForwad/LeaveCarryForwardMain.jsx
src/views/HrReports/AttendenceReport/InactiveEmployeeAttendnaceReport.jsx
src/views/MuiComponents/JoyComponent/InactiveEmployeeSelect.jsx

corrections

---

src/views/Attendance/SalaryProcess/SalaryProcessFunctions.js

earn deduction null correction

earn deduction null correction

---

src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/LeaveManagement/CommonRequest/CommonReqstComponent/OnDutyRequest.jsx

attendnace view correction

---

src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewList.jsx
src/views/LeaveManagement/ApprovalHR/LeaveApprovalHR.jsx
src/views/LeaveManagement/CommonRequest/Approvals/Modals/OneHourReqstModal.jsx

dashborad count correction

---

src/views/EmployeeRecord/ContractRenewalProcess/ContractRenewalProcess.jsx
src/views/EmployeeRecord/ContractRenewalProcess/Direct_Contract_Close.jsx

contract detl correction

---

src/views/Attendance/PreviousMonthReport/EmployeeView.jsx
src/views/Attendance/PreviousMonthReport/InchargeHodView.jsx
src/views/Attendance/PreviousMonthReport/MasterView.jsx
src/views/LeaveManagement/OffRequest/RequestComponents/DoffSubmitForm.jsx

corrected doff request HP

---

src/views/Attendance/AttendanceView/AttendanceView.jsx
src/views/Attendance/ShiftUpdation/BasedonSecondPolicy.jsx
src/views/LeaveManagement/LeaveReports/LeaveReportMain.jsx

not hod or incharge cant view the master page correction

not hod or incharge cant view the master page correction

---

src/routes.js
src/views/Attendance/PunchMarkingHR/MonthlyAttendanceProcess.jsx
src/views/Attendance/ShiftUpdation/BasedonSecondPolicy.jsx
src/views/Attendance/ShiftUpdation/Function.js
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/Attendance/ShiftUpdation/TableRows.jsx
src/views/Resignation/EndOfService/EndofProcess.jsx

error correction after live

---

src/views/Attendance/AttendanceView/EmployeeCompnt.jsx
src/views/Attendance/AttendanceView/InchargeHodCompnt.jsx
src/views/Attendance/PunchMarkingHR/punchMarkingHrFunc.js
src/views/HrReports/AttendenceReport/AttendenceReport.jsx

attendance report all

---

src/views/Attendance/PreviousMonthReport/MasterView.jsx
src/views/Attendance/PunchMarkingHR/PunchMarkingHR.jsx

attendnace punch view data length=0 not showing warning

attendnace punch view data length=0 not showing warning

---

src/views/Attendance/PreviousMonthReport/EmployeeView.jsx
src/views/Attendance/PreviousMonthReport/InchargeHodView.jsx
src/views/Attendance/PreviousMonthReport/MasterView.jsx
src/views/Attendance/ShiftUpdation/ShiftModal.jsx
src/views/Attendance/ShiftUpdation/TableRows.jsx
src/views/EmployeeRecord/EmployeeFile/EmployeeProfile/EmpMenus/Statutory/StatutoryInformation.jsx
src/views/LeaveManagement/CompOffRequest/OffSubmitForm.jsx

cod=ff slected time copmarison error correction

codff slected time copmarison error correction

---

src/views/LeaveManagement/ApprovalHR/Modal/LeaveRequestModal.jsx
src/views/LeaveManagement/LeaveCommonComponent/LeavRqModel.jsx

Include a new feature in the Training section to enable the addition of new training programs

Include a new feature in the Training section to enable the addition of new training programs

---

src/views/TrainingDevelopment/TrainingDetails/PdfInductionTranning.js
src/views/TrainingDevelopment/TrainingDetails/PdfTranning.js

Change logo path

---

src/views/Attendance/DepartmentSecChange/DepartmentSecChange.jsx
src/views/Attendance/ShiftUpdation/ShiftUpdation.jsx
src/views/LeaveManagement/LeavereRequsition/MissPunchRequest/MissPunchRequest.jsx

department section change component undefined error correction

department section change component undefined error correction

---

src/views/Component/ReduxComponent/SectionBsdEmployee.jsx
src/views/MuiComponents/JoyComponent/JoyBranchSelect.jsx
src/views/MuiComponents/JoyComponent/JoyDesignationSelect.jsx
src/views/MuiComponents/JoyComponent/JoyInstitutionSelect.jsx

corrected showing undefined in sectionbased employee select component

corrected showing undefined in sectionbased employee select component
